#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrdb -merge .Xresources
~/.fehbg &
tint2 &
setxkbmap -layout "us,ir" -option "grp:alt_shift_toggle"
diodon &
xsetroot -cursor_name left_ptr &
xset dpms 0 0 10000

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width	1
bspc config window_gap		0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

bspc rule -a Pavucontrol state=floating focus=on
bspc rule -a '*:*:nmtui' state=floating focus=on
#bspc rule -a TelegramDesktop state=floating focus=on
#bspc rule -a KeePassXC state=floating focus=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
